# Generated by Django 4.0.3 on 2023-04-28 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(db_column='category_name', max_length=50)),
                ('category_uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('child_category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('child_category_name', models.CharField(db_column='child_category_name', max_length=50)),
                ('category_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('details', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=None)),
                ('description', models.CharField(max_length=3000)),
                ('product_images', models.FileField(default=None, upload_to='media/')),
                ('add_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='add on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_id', models.ManyToManyField(to='users.product')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.FileField(upload_to='media/')),
                ('product_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product')),
            ],
        ),
        migrations.CreateModel(
            name='GrantChildCategory',
            fields=[
                ('grant_child_category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('grant_child_category_name', models.CharField(db_column='grant_child_category_name', max_length=50)),
                ('child_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.childcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone', models.BigIntegerField()),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated on')),
                ('address', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
