# Generated by Django 4.0.3 on 2023-11-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
