# Generated by Django 4.0.3 on 2023-05-14 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='created at'),
        ),
    ]
