# Generated by Django 4.0.3 on 2023-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_productcategory_parent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
