# Generated by Django 4.0.3 on 2024-01-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('visit_count', models.PositiveBigIntegerField(default=None, null=True)),
                ('product_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
