# Generated by Django 4.0.3 on 2024-01-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productutils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productutils',
            old_name='product_image_id',
            new_name='product_id',
        ),
    ]
