# Generated by Django 4.0.3 on 2023-05-15 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_column='category_name', max_length=70)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='created at')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('parent_id', models.ForeignKey(blank=True, default='Parent Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
